version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lara_proyecto_web
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
    depends_on:
      - db
    networks:
      - backend
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  db:
    image: mysql:8.0
    container_name: lara_proyecto_mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: viajes
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: lara_proyecto_phpmyadmin
    depends_on:
      - db
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    networks:
      - backend

volumes:
  mysql_data:


networks:
  backend:
    driver: bridge
